export const SET_IMGS_REQUEST = 'SET_IMGS_REQUEST';
export const SET_IMGS_SUCCESS = 'SET_IMGS_SUCCESS';
export const SET_IMGS_FAILED = 'SET_IMGS_FAILED';
export const SET_IMGS_CLEAR = 'SET_IMGS_CLEAR';